specVersion: "0.3.0"

name: "terra-subql-starter"
version: "0.0.1"
description: "This project can be use as a starting point for developing your Terra based SubQuery project"
repository: "https://github.com/subquery/terra-subql-starter"

schema:
  file: "./schema.graphql"

network:
  chainId: "columbus-5" # Terra network code
  endpoint: "https://terra-columbus-5.api.onfinality.io"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/terra-columbus-5-dictionary"

dataSources:
  - kind: terra/Runtime
    startBlock: 6747920
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: terra/BlockHandler
        - handler: handleTransaction
          kind: terra/TransactionHandler
        - handler: handleEvent
          kind: terra/EventHandler
          filter:
            type: transfer
            messageFilter:
              type: "/terra.wasm.v1beta1.MsgExecuteContract"
              values:
                contract: "terra1j66jatn3k50hjtg2xemnjm8s7y8dws9xqa5y8w"
        - handler: handleMessage
          kind: terra/MessageHandler
          filter:
            type: "/terra.wasm.v1beta1.MsgExecuteContract"
            values:
              contract: "terra1j66jatn3k50hjtg2xemnjm8s7y8dws9xqa5y8w"
